{{- if and .Values.clusterRole.create .Values.kubernetes.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
  labels:
    app: {{ include "tagwatcher-agent.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
  labels:
    app: {{ include "tagwatcher-agent.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tagwatcher-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
  namespace: {{ default .Release.Namespace .Values.kubernetes.namespace }}
  labels:
    app: {{ include "tagwatcher-agent.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
  namespace: {{ default .Release.Namespace .Values.kubernetes.namespace }}
  labels:
    app: {{ include "tagwatcher-agent.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tagwatcher-agent.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tagwatcher-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
