{{- if .Values.tagwatcher.registrationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tagwatcher-agent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tagwatcher-agent.name" . }}
type: Opaque
stringData:
  registrationToken: {{ .Values.tagwatcher.registrationToken | quote }}
{{- end }}
